import os
from timeit import default_timer as timer
start = timer()
os.system('mvn exec:java -Dexec.mainClass=org.semanticweb.rulewerk.examples.Exp -e')
os.system('mvn exec:java -Dexec.mainClass=org.semanticweb.rulewerk.examples.Exp -e')
os.system('mvn exec:java -Dexec.mainClass=org.semanticweb.rulewerk.examples.Exp -e')
os.system('mvn exec:java -Dexec.mainClass=org.semanticweb.rulewerk.examples.Exp -e')
os.system('mvn exec:java -Dexec.mainClass=org.semanticweb.rulewerk.examples.Exp -e')
os.system('mvn exec:java -Dexec.mainClass=org.semanticweb.rulewerk.examples.Exp -e')
os.system('mvn exec:java -Dexec.mainClass=org.semanticweb.rulewerk.examples.Exp -e')
os.system('mvn exec:java -Dexec.mainClass=org.semanticweb.rulewerk.examples.Exp -e')
os.system('mvn exec:java -Dexec.mainClass=org.semanticweb.rulewerk.examples.Exp -e')
os.system('mvn exec:java -Dexec.mainClass=org.semanticweb.rulewerk.examples.Exp -e')
os.system('mvn exec:java -Dexec.mainClass=org.semanticweb.rulewerk.examples.Exp -e')
os.system('mvn exec:java -Dexec.mainClass=org.semanticweb.rulewerk.examples.Exp -e')
os.system('mvn exec:java -Dexec.mainClass=org.semanticweb.rulewerk.examples.Exp -e')
os.system('mvn exec:java -Dexec.mainClass=org.semanticweb.rulewerk.examples.Exp -e')
os.system('mvn exec:java -Dexec.mainClass=org.semanticweb.rulewerk.examples.Exp -e')
os.system('mvn exec:java -Dexec.mainClass=org.semanticweb.rulewerk.examples.Exp -e')
os.system('mvn exec:java -Dexec.mainClass=org.semanticweb.rulewerk.examples.Exp -e')
os.system('mvn exec:java -Dexec.mainClass=org.semanticweb.rulewerk.examples.Exp -e')
os.system('mvn exec:java -Dexec.mainClass=org.semanticweb.rulewerk.examples.Exp -e')
os.system('mvn exec:java -Dexec.mainClass=org.semanticweb.rulewerk.examples.Exp -e')
end = timer()
print(end - start)