package org.semanticweb.vlog4j.owlapi;

/*-
 * #%L
 * VLog4j OWL API Support
 * %%
 * Copyright (C) 2018 VLog4j Developers
 * %%
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * #L%
 */

import java.util.Set;

import org.semanticweb.owlapi.model.OWLAxiom;
import org.semanticweb.owlapi.model.OWLOntology;
import org.semanticweb.vlog4j.core.model.api.Atom;
import org.semanticweb.vlog4j.core.model.api.Rule;

/**
 * Class for converting OWL ontologies to rules.
 * 
 * @author Markus Kroetzsch
 *
 */
public class OwlToRulesConverter {

	final OwlAxiomToRulesConverter owlAxiomToRulesConverter = new OwlAxiomToRulesConverter();

	/**
	 * Converts the given OWL ontology to rules and facts, and adds the result to
	 * the internal buffer of rules and facts for later retrieval.
	 * 
	 * @param owlOntology
	 *            the ontology
	 */
	public void addOntology(OWLOntology owlOntology) {
		for (OWLAxiom owlAxiom : owlOntology.getAxioms()) {
			owlAxiom.accept(this.owlAxiomToRulesConverter);
		}
	}

	/**
	 * Returns the set of facts generated by transforming the given OWL ontology. No
	 * copy is created, so the set should not be modified if its owner is still to
	 * be used.
	 * 
	 * @return set of facts
	 */
	public Set<Atom> getFacts() {
		return this.owlAxiomToRulesConverter.facts;
	}

	/**
	 * Returns the set of rules generated by transforming the given OWL ontology. No
	 * copy is created, so the set should not be modified if its owner is still to
	 * be used.
	 * 
	 * @return set of rules
	 */
	public Set<Rule> getRules() {
		return this.owlAxiomToRulesConverter.rules;
	}

}
